application: usellapp
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: "1.2"

handlers:

- url: /static
  static_dir: static

- url: /
  script: main.py

- url: /post
  script: post.py

- url: /seller_profile
  script: seller_profile.py

- url: /search=.*
  script: search.py

- url: /edit_item=.*
  script: edit_page.py

- url: /upload
  script: upload.py

- url: /view_photo/.*
  script: photo_viewer.py